# Generated by Django 4.1.1 on 2024-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=20),
            preserve_default=False,
        ),
    ]
