# Generated by Django 4.1.1 on 2024-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0003_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
